// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public class ArrivalInstruction
{
    [Key] public int Id { get; set; }

    public string CompanyId { get; set; }

    public int ScheduledArrivalNumber { get; set; }

    public DateTime ScheduledArrivalDate { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public int Quantity { get; set; }

    public string OrderNumber { get; set; }

    public DateTime OrderDate { get; set; }

    public int SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string DataKey { get; set; }

    public string CreateOperatorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string UpdateOperatorId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsDeleted { get; set; }
}