// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public partial class Channel
{
    [Key] public string ChannelCode { get; set; }

    public string CompanyId { get; set; }

    public string ChannelName { get; set; }

    public string ChannelMasterCode { get; set; }

    public string ChannelMasterName { get; set; }

    public string PaymentMethod { get; set; }

    public string BillCalcType { get; set; }

    public string Currency { get; set; }

    public string LanguageCode { get; set; }

    public bool? IsActive { get; set; }

    public string DataKey { get; set; }

    public string CreateOperatorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string UpdateOperatorId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ChannelMaster ChannelMasterCodeNavigation { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}