// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public partial class Company
{
    [Key] public Guid CompanyTenantId { get; set; }

    public string FullName { get; set; }

    public string ShortName { get; set; }

    public string DataKey { get; set; }

    public int AuthPtenantId { get; set; }

    public bool? IsDeleted { get; set; }
}