// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public partial class ExchangeRate
{
    [Key] public int Id { get; set; }

    public string CurrencyCodeFrom { get; set; }

    public string CurrencyCodeTo { get; set; }

    public string Period { get; set; }

    public double Rate { get; set; }

    public DateTime AcquisitionDate { get; set; }

    public string DataKey { get; set; }

    public string CreateOperatorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string UpdateOperatorId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsDeleted { get; set; }
}