// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public partial class OrderItem
{
    [Key] public int Id { get; set; }

    public int OrderHeaderId { get; set; }

    public string CompanyId { get; set; }

    public string OrderId { get; set; }

    public int? LineNo { get; set; }

    public string SalesProductCode { get; set; }

    public string SalesProductName { get; set; }

    public int? Quantity { get; set; }

    public double? PurchaseUnitPrice { get; set; }

    public double? DeclaredValue { get; set; }

    public string Currency { get; set; }

    public int? ReturnQuantity { get; set; }

    public string DataKey { get; set; }

    public string CreateOperatorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string UpdateOperatorId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Order OrderHeader { get; set; }
}