// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public partial class Order
{
    [Key] public int Id { get; set; }

    public string CompanyId { get; set; }

    public string WarehouseCode { get; set; }

    public string ChannelCode { get; set; }

    public string OrderId { get; set; }

    public string OrderStatus { get; set; }

    public DateTime? OrderDate { get; set; }

    public double? Total { get; set; }

    public double? SubTotal { get; set; }

    public double? HandlingCharge { get; set; }

    public double? Giftvoucher { get; set; }

    public double? Point { get; set; }

    public double? Shipping { get; set; }

    public double? CodCharge { get; set; }

    public double? DiscountAmount { get; set; }

    public double? OtherDiscount { get; set; }

    public double? TaxAmount { get; set; }

    public string Currency { get; set; }

    public string DeliveryCity { get; set; }

    public string DeliveryState { get; set; }

    public string DeliveryCountryCode { get; set; }

    public string DeliveryCountryName { get; set; }

    public string DeliveryMail { get; set; }

    public string BillCity { get; set; }

    public string BillState { get; set; }

    public string BillCountry { get; set; }

    public string BillMail { get; set; }

    public string OrderDeliveryCompany { get; set; }

    public string Remarks { get; set; }

    public string InternalRemarks { get; set; }

    public string ReturnStatus { get; set; }

    public DateTime? ShippedDate { get; set; }

    public bool? IsDeltaData { get; set; }

    public string DataKey { get; set; }

    public string CreateOperatorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string UpdateOperatorId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Channel ChannelCodeNavigation { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<OrderReturnItem> OrderReturnItems { get; set; } = new List<OrderReturnItem>();
}