// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entity.WMS;
using Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entity.Commons;
[Table("ProductJanCodes")]
public partial class ProductJanCode : GenericEntity
{
    [Key] public int Id { get; set; }

    public string JanCode { get; set; }

    public string JanDescription { get; set; }    

    public int ProductId { get; set; }
    public EnumStatus Status { get; set; } = EnumStatus.Activated;
}