// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entity.WMS;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public class Supplier : GenericEntity
{
    [Key] public int Id { get; set; }

    public string? SupplierName { get; set; }

    public int? TenantId { get; set; }

    public string? SupplierId { get; set; }
}