// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Commons;

public partial class SystemClassCompany
{
    [Key] public int Id { get; set; }

    public string CompanyId { get; set; }

    public string LargeClassCode { get; set; }

    public string SmallClassCode { get; set; }

    public string LargeClassCodeName { get; set; }

    public string SmallClassCodeName { get; set; }

    public string Code1 { get; set; }

    public string Code2 { get; set; }

    public int? Numeric1 { get; set; }

    public double? Numeric2 { get; set; }

    public DateTime? Date1 { get; set; }

    public DateTime? Date2 { get; set; }

    public string Text1 { get; set; }

    public string Text2 { get; set; }

    public string Remarks { get; set; }

    public string DataKey { get; set; }

    public string CreateOperatorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string UpdateOperatorId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsDeleted { get; set; }
}