// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entity.WMS;
using Domain.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entity.Commons;
[Table("Vendors")]
public partial class Vendor : GenericEntity
{
    [Key] public int Id { get; set; }

    public string VendorCode { get; set; }

    public string VendorName { get; set; }

    public string VendorCompanyName { get; set; }

    public string DeadOfficeAddress { get; set; }

    public string HeadOfficePhone { get; set; }

    public string HeadOfficeFax { get; set; }

    public string BillingAddress { get; set; }

    public string BillingContactName { get; set; }

    public string BillingPhone { get; set; }

    public string BillingFax { get; set; }

    public string BillingMail { get; set; }

    public string BankName { get; set; }

    public string BankBranch { get; set; }

    public string BankAccountType { get; set; }

    public string BankAccountNumber { get; set; }

    public string BankAccountHolder { get; set; }

    public string Remarks { get; set; }

    public double? JamCharge { get; set; }

    public int? BillingDate { get; set; }

    public string DataKey { get; set; }
    public EnumStatus Status { get; set; } = EnumStatus.Activated;
}