// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entity.Commons;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entity.authp.Commons;
[Table("AuthUser")]
public partial class AuthUser
{
    [Key] public string UserId { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public int? TenantId { get; set; }

    public byte[] ConcurrencyToken { get; set; }

    public bool IsDisabled { get; set; }

    public virtual TenantAuth Tenant { get; set; }

    public virtual ICollection<UserToRole> UserToRoles { get; set; } = new List<UserToRole>();
}