// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entity.authp.Commons;

[Table("RefreshToken")]
public partial class RefreshTokenAuth
{
    [Key] public string TokenValue { get; set; }

    public string UserId { get; set; }

    public string JwtId { get; set; }

    public bool IsInvalid { get; set; } = true;

    public DateTime AddedDateUtc { get; set; }

    public byte[] ConcurrencyToken { get; set; }
}