// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entity.authp.Commons;

[Table("RoleToPermissionsTenant")]
public partial class RoleToPermissionsTenantAuth
{
    [Key] public string TenantRolesRoleName { get; set; }

    public int TenantsTenantId { get; set; }

    public byte[] ConcurrencyToken { get; set; }

    public virtual RoleToPermissionAuth TenantRolesRoleNameNavigation { get; set; }

    public virtual TenantAuth TenantsTenant { get; set; }
}