// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entity.authp.Commons;

[Table("RoleToPermission")]
public partial class RoleToPermissionAuth
{
    [Key] public string RoleName { get; set; }

    public string Description { get; set; }

    public string PackedPermissionsInRole { get; set; }

    public byte[] ConcurrencyToken { get; set; }

    public byte RoleType { get; set; }

    public virtual ICollection<RoleToPermissionsTenantAuth> RoleToPermissionsTenants { get; set; } = new List<RoleToPermissionsTenantAuth>();

    public virtual ICollection<UserToRole> UserToRoles { get; set; } = new List<UserToRole>();
}