// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.authp.Commons;

public partial class UserToRole
{
    [Key] public string UserId { get; set; }

    public string RoleName { get; set; }

    public byte[] ConcurrencyToken { get; set; }

    public virtual RoleToPermissionAuth RoleNameNavigation { get; set; }

    public virtual AuthUser User { get; set; }
}